name: Test workflow
on: [push]

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            -   name: Print true as json
                id: bar
                run: echo ::set-output name=foo::false
        outputs:
            foo: fromJSON(steps.bar.outputs.foo)

    test-2:
        runs-on: ubuntu-latest
        needs: test-1
        if: needs.test-1.outputs.foo
        container:
            image: archlinux
        steps:
            -   name: Show disk usage
                run: echo ${{ needs.test-1.outputs.foo }}
