name: Test workflow
on: [push]

jobs:
    test-package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build progress
              uses: './.github/actions/build'