name: Test workflow
on: [push]

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            - name: nothing
              run: echo nothing
            - name: artifact
              run: echo "x" > x
            - uses: actions/upload-artifact@v2
              with:
                  name: test
                  path: x
        outputs:
            a: "b"
    test-2:
        needs: test-1
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup action
              run: npm run setup --prefix ./.github/actions/build
            - name: Run action
              uses: ./.github/actions/build
              with:
                  token: "${{ secrets.GITHUB_TOKEN }}"