name: Test workflow
on: [push]

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            - name: Log into registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - name: Pust image to ghcr
              run: docker pull alpine && docker tag alpine ghcr.io/networkexception/workflow-testing && docker push ghcr.io/networkexception/workflow-testing
        outputs:
            a: "b"
    test-2:
        needs: test-1
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup action
              run: npm run setup --prefix ./.github/actions/build
            - name: Run action
              uses: ./.github/actions/build
              with:
                  token: "${{ secrets.GITHUB_TOKEN }}"