name: Build ungoogled-chromium-archlinux for testing
on: [push, pull_request]

jobs:
    a:
        runs-on: ubuntu-latest
        container: docker.pkg.github.com/ungoogled-software/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux-testing:latest
        steps:
            - name: get package
              run: wget https://download.opensuse.org/repositories/home:/ungoogled_chromium:/testing/Arch/x86_64/ungoogled-chromium-89.0.4389.114-2-x86_64.pkg.tar.zst
            - name: Install package
              run: docker run pacman -U ungoogled-chromium-*.pkg.*
            - name: Test package
              run: chromium --version