name: Test workflow
on: [push]

jobs:
    test-1:
        runs-on: ubuntu-latest
        container: archlinux
        steps:
            - name: Test criu
              run: pacman -Sy criu --noconfirm && criu check
