name: Test workflow
on: [push]

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            -   name: Print true as json
                run: echo ${{ toJSON(true) }}

    test-2:
        runs-on: ubuntu-latest
        container:
            image: archlinux
        steps:
            -   name: Show disk usage
                run: df -h
