name: Test workflow
on:
    push:
    workflow_dispatch:
        inputs:
            test:
                description: "something something"
                required: true
                type: choice
                options:
                    - "a"
                    - "b"

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            -   name: Print all mountpoints
                run: sudo findmnt
