name: Test workflow
on:
    push:
    workflow_dispatch:
        inputs:
            test:
                description: "something something"
                required: true
                type: choice
                options:
                    - "a"
                    - "b"

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            -   name: "Install Nix"
                uses: cachix/install-nix-action@v18
                with:
                    install_url: https://releases.nixos.org/nix/nix-2.13.3/install
            -   name: Print all mountpoints
                run: sudo findmnt
