name: Test workflow
on: [push]

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            - name: Test criu
              run: sudo add-apt-repository ppa:criu/ppa -yu && sudo apt install criu && sudo criu check
