name: Build ungoogled-chromium-archlinux for testing
on: [push, pull_request]

jobs:
    test-package:
        runs-on: ubuntu-latest
        steps:
            - name: Log into registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
            - name: Pull image
              run: docker pull "docker.pkg.github.com/ungoogled-software/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux-testing:latest"
            - name: Download package
              run: wget https://nwex.de/package
            - name: Run container
              run: docker run
                  --name "package"
                  --entrypoint /bin/bash
                  --mount type=bind,source="$(pwd)/package",target=/home/build/package
                  "docker.pkg.github.com/ungoogled-software/ungoogled-chromium-archlinux/ungoogled-chromium-archlinux-testing:latest"
                   -c 'sudo pacman -U /home/build/package && chromium --version'