name: Test workflow
on:
    push:
    workflow_dispatch:
        inputs:
            test:
                description: "something something"
                required: true
                options:
                    - "a"
                    - "b"

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            -   name: Print test
                run: echo ${{ github.event.inputs.test }}

