name: Build ungoogled-chromium-archlinux for testing
on: [push, pull_request]

jobs:
    test-package:
        runs-on: ubuntu-latest
        steps:
            - name: Set variables
              id: variables
              run: |
                echo "::set-output name=a::yes"
                echo "::set-output name=b::yes"
                echo "::set-output name=c::no"
            - name: Should run
              if: ${{ steps.variables.outputs.a == 'yes' && steps.variables.outputs.b == 'yes' }}
              run: echo yes
            - name: Should not run
              if: ${{ steps.variables.outputs.b == 'yes' && steps.variables.outputs.c == 'yes' }}
              run: echo no