name: Test workflow
on: [push]

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            -   name: Test
                id: test
                run: echo '::set-output name=finished::yes'
        outputs:
            finished: steps.test.outputs.finished

    test-2:
        runs-on: ubuntu-latest
        needs: test-1
        if: ${{ needs.test-1.outputs.finished != 'yes' }}
        steps:
            -   name: Test
                id: test
                run: echo '::set-output name=finished::yes'
