name: Test workflow
on: [push]

jobs:
    test-package:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup action
              run: npm install --prefix ./.github/actions/build
            - name: Build progress
              uses: ./.github/actions/build