name: Test workflow
on: [push]

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            - name: Test criu
              run: add-apt-repository ppa:criu/ppa -yu && apt install criu && criu check
