name: Test workflow
on:
    push:
    workflow_dispatch:
        inputs:
            test:
                description: "something something"
                required: true
                type: choice
                options:
                    - "a"
                    - "b"

jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            -   name: "Install Nix"
                uses: cachix/install-nix-action@v18
                with:
                    install_url: https://releases.nixos.org/nix/nix-2.13.3/install
            -   name: Print all mountpoints
                run: sudo findmnt

    test-2:
        runs-on: ubuntu-latest
        container:
            image: archlinux
            volumes:
                - /:/host
        steps:
            - name: Free space on runner
              run: |
                  pacman -Syu --needed --noconfirm docker base-devel duf

                  duf

                  sudo rm -rf /host/usr/share/dotnet
                  sudo rm -rf /host/usr/local/lib/android
                  sudo rm -rf /host/opt/ghc
                  sudo rm -rf /host/opt/hostedtoolcache/CodeQL
                  sudo docker image prune --all --force

                  duf
